<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="sts2-decompiled/**" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="sts2">
        <HintPath>$(SlayTheSpireDataPath)/sts2.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="GodotSharp">
        <HintPath>$(SlayTheSpireDataPath)/GodotSharp.dll</HintPath>
        <Private>false</Private>
      </Reference>
      <Reference Include="0Harmony">
        <HintPath>$(SlayTheSpireDataPath)/0Harmony.dll</HintPath>
        <Private>false</Private>
      </Reference>
    </ItemGroup>

 
    <Target Name="PostBuild" AfterTargets="Build">
      <MakeDir Directories="$(SlayTheSpireDataPath)/../mods/" />
      <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SlayTheSpireDataPath)/../mods/" SkipUnchangedFiles="true" />
      <Copy SourceFiles="neuro-sts2.json" DestinationFolder="$(SlayTheSpireDataPath)/../mods/" SkipUnchangedFiles="true" />
    </Target>
</Project>
