<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="sts2-decompiled/**" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="sts2">
        <HintPath>$(SlayTheSpireDataPath)/sts2.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="GodotSharp" Version="4.7.0-dev.2" />
      <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    </ItemGroup>

 
    <Target Name="PostBuild" AfterTargets="Build">
      <MakeDir Directories="$(SlayTheSpireDataPath)/../mods/" />
      <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(SlayTheSpireDataPath)/../mods/" SkipUnchangedFiles="true" />
    </Target>
</Project>
